### ISSUE TITLE
Cannot change the Extended PANID

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#189]
With ZGUI (as well as with the API), I'm not able to change the Extended PANID

Here after is the screenshot of:
- setting Channel to 26
- Setting ExtPANID to 0x00124b00198d7521
- Setting COORDINATOR

-> Start NWK
-> Network State

All Commands get an Ok Status !!
![Capture](https://user-images.githubusercontent.com/8291674/56077982-db9cf700-5de2-11e9-972e-b35dc2fbd191.PNG)

**Comment by pipiche38** [comment]
However if you set 0x0 as the extended PANID parameter it is taken into account and you get the Extended PANID reset!

**Comment by pipiche38** [comment]
After further investigation, I have been able to force a specific Extended PANID only after an Erase PDM.

So for me there are some inconsistency : 

(1) If you need Erase PDM prior to set a specific Extended PANID (and that could make sense), if we are not in such case, Zigate should return an error and not send 0x8000 with 0x00 Status
(2) In case you set ExtendedPANID to 0 whatever is the situation of the PDM (Erased or not), you get a new Extended PANID. Which then is inconsistent with (1)

**Comment by pipiche38** [comment]
any idea ?

**Comment by ISO-B** [comment]
If PANID is 0x00 when you start forming network ZiGate will generate random id.

You probably can't and should not be able to change PANID after forming and starting network. This is probably reason why you can't change panid without PDM reset. More info: JN-UG-3113 v1.5 Chapter 5.1.1

There might be bug in function ZPS_eAplAibSetApsUseExtendedPanId() that is used to set panid, which lets you to reset panid at anytime. If thats case we can't do nothing, because its inside nxp library files that can't be edited because they don't share source code for those.

**Comment by pipiche38** [comment]
Would it makes sense to have a deterministic way implemented in ZiGate ?

And si return an error if network is already formed ?

**Comment by ISO-B** [comment]
Yes, that might be good solution to prevent changing coordinators panid after network formation. I will implement it later this weekend.
